In [1]:
!pip install pandas numpy scikit-learn matplotlib

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (2.4.4)
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: matplotlib in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (3.10.8)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: scipy>=1.10.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
df = pd.read_csv("spam.csv", encoding="latin-1")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'spam.csv'

In [4]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\hp\CreditCardFraudDetection
['.ipynb_checkpoints', 'CreditCardFraudDetection.ipynb.ipynb', 'fraud_detection_model.pkl', 'SpamSMSDetection.ipynb']

In [5]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'CreditCardFraudDetection.ipynb.ipynb', 'fraud_detection_model.pkl', 'SpamSMSDetection.ipynb']

In [6]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'CreditCardFraudDetection.ipynb.ipynb', 'fraud_detection_model.pkl', 'SpamSMSDetection.ipynb']

In [7]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\hp\Downloads\archive (6)\spam.csv",
    encoding="latin-1"
)

df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [8]:
df = df[['v1', 'v2']]

df.columns = ['label', 'message']

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df['label'] = df['label'].map({
    'ham': 0,
    'spam': 1
})

df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [10]:
print(df.shape)

print(df['label'].value_counts())

(5572, 2)
label
0    4825
1     747
Name: count, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

X = df['message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [13]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [14]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)

print(cm)

NameError: name 'pred' is not defined

In [15]:
from sklearn.metrics import accuracy_score, classification_report

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))
print(classification_report(y_test, pred))

Accuracy: 0.9623318385650225
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       1.00      0.72      0.84       150

    accuracy                           0.96      1115
   macro avg       0.98      0.86      0.91      1115
weighted avg       0.96      0.96      0.96      1115

In [16]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)

print(cm)

[[965   0]
 [ 42 108]]

In [17]:
import joblib

joblib.dump(model, "spam_sms_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("Model Saved Successfully")

Model Saved Successfully

In [18]:
message = ["Congratulations! You have won a free iPhone. Click now!"]

msg_vector = vectorizer.transform(message)

prediction = model.predict(msg_vector)

if prediction[0] == 1:
    print("Spam Message")
else:
    print("Not Spam")

Spam Message

In [19]:
import joblib

joblib.dump(model, "spam_sms_model.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("Files Saved Successfully")

Files Saved Successfully

In [20]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'CreditCardFraudDetection.ipynb.ipynb', 'fraud_detection_model.pkl', 'SpamSMSDetection.ipynb', 'spam_sms_model.pkl', 'tfidf_vectorizer.pkl']